# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        # NOTE: To enable Github Actions for CI/CD remove 'false' condition 👇
        if: false && ${{ !contains(github.event.head_commit.message, 'skip-ci') }}

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                repository: ${{ github.event.pull_request.head.repo.full_name }}
                ref: ${{ github.event.pull_request.head.ref }}
                
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@octocat'
            - uses: oven-sh/setup-bun@v2

            - run: bun install
            - run: bun run build
            - name: bun run bump
              if: github.ref == 'refs/heads/main'
              run: |
                  git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
                  git config user.name "$GITHUB_ACTOR"
                  yarn bump
              env:
                  # NOTE: Make sure to set up your NPM secret in Github
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}